name: Fetch VLESS Config

on:
  schedule:
    - cron: "0 */2 * * *" # هر ۲ ساعت
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install telethon

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
        run: python fetch_vless.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.txt
          git commit -m "Update output"
          git push
